name: hotel_list_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: any
  flutter_riverpod: ^2.6.1
  app_links: ^6.4.0
  riverpod_annotation: ^2.6.1
  top_snackbar_flutter: ^3.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  google_maps_flutter: ^2.12.1
  get_it: ^8.0.3
  flutter_svg: ^2.1.0
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.13.0
  dio_cookie_manager: ^3.1.0
  cookie_jar: ^4.0.5
  dio: ^5.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  test: ^1.24.9
  mockito: ^5.4.4
  build_runner: ^2.4.13
  network_image_mock: ^2.0.0


  integration_test:
    sdk: flutter
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  json_serializable: ^6.8.0



flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
    - assets/icons/



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_intl:
  enabled: true
