name: Build & Upload (Android, iOS)



on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main



jobs:
  main:
    runs-on: macos-latest


    steps:


      - name: Clone repository
        uses: actions/checkout@v4


      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "18.x"


      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.1'
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"


      - name: Get Flutter packages
        run: |
          flutter pub get





#      - name: Run all tests
#        run: |
#          flutter test


      - name: Build APK
        run: |
          flutter build apk


      - name: Flutter build ipa
        run: |
          flutter build ipa --no-codesign


      - name: Compress Archives and IPAs
        run: |
          cd build
          tar -czf ios_build.tar.gz ios


#      - name: Upload Artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: Releases
#          path: |
#            build/app/outputs/flutter-apk/app-release.apk
#            build/ios_build.tar.gz